# Generated by Django 4.1 on 2022-09-26 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commandString', models.CharField(max_length=100)),
                ('sendCommand', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('statement', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('starting_stage', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('difficulty', models.IntegerField(default=1)),
                ('apoyo_deslizante', models.IntegerField(default=0)),
                ('apoyo_fijo', models.IntegerField(default=0)),
                ('empotramiento', models.IntegerField(default=0)),
                ('rotula', models.IntegerField(default=0)),
                ('biela', models.IntegerField(default=0)),
                ('fuerza_distribuida', models.IntegerField(default=0)),
                ('fuerza_angular', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stage', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('apoyo_deslizante', models.IntegerField(default=0)),
                ('apoyo_fijo', models.IntegerField(default=0)),
                ('empotramiento', models.IntegerField(default=0)),
                ('rotula', models.IntegerField(default=0)),
                ('viela', models.IntegerField(default=0)),
                ('fuerza_distribuida', models.IntegerField(default=0)),
                ('fuerza_angular', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
