# Generated by Django 4.1 on 2022-09-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
